import Head from "next/head";
import { Inter } from "@next/font/google";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  let [count, setCount] = useState(0);

  const handleDecrement = () => {
    if (count === 0) return false;

    setCount(count - 1);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-6xl mx-auto bg-gray-800 w-4/5 md:w-4/5 lg:w-2/3 rounded-2xl pb-20 mt-32">
        <h1 className="text-4xl text-center pt-10 font-semibold text-orange-500 border-b pb-8 rounded-2xl bg-gray-900 ">
          Click Counter App{" "}
        </h1>
        <h2 className="text-center text-7xl text-orange-500 mt-20 font-bold bg-gray-800 py-20 rounded-2xl w-96 mx-auto shadow-lg border border-white">
          {count}
        </h2>
        <div className="flex justify-around gap-4 w-1/3 mx-auto text-2xl cursor-pointer">
          
          <button
            className="bg-orange-500 px-16 py-2 rounded-md -mt-4 shadow-xl hover:shadow-2xl active:scale-90 transition-transform duration-150 ease-in border border-white"
            onClick={handleDecrement}
          >
            -
          </button>
<button
            className="bg-orange-500 px-16 py-2 rounded-md -mt-4 shadow-xl hover:shadow-2xl active:scale-90 transition-transform duration-150 ease-in border border-white"
            onClick={() => setCount(count + 1)}
          >
            +
          </button>
        </div>
      </main>
    </>
  );
}
